name: Update wakatime stats

on:
  workflow_dispatch:
  schedule:
    - cron: "15 */8 * * *"

jobs:
  build:
    name: Update-wakatime-stats
    runs-on: ubuntu-latest
    env:
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      GH_TOKEN: ${{ secrets.GIT_TOKEN }}
      UPDATE_OPTION: GIST_AND_MARKDOWN
      MARKDOWN_FILE: README.md
      GIST_ID: "595eec8ae8745b516c9a8ad8a265a100"
      GIST_BARSTYLE: SOLIDLT
      GIST_BARLENGTH: -1
      GIST_TIMESTYLE: SHORT

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v6
        with:
          go-version: ^1.14
        id: go
      - name: Check out repo
        uses: actions/checkout@v6
      - uses: actions/setup-go@v6
      - name: Clone and run waka-box
        run: |-
          git clone https://github.com/XiaoMiku01/waka-box-go.git 
          cd waka-box-go && go build -o waka ./cmd/box/main.go
          mv ./waka ../ && cd .. && rm -rf waka-box-go/
      - name: Commit and push
        run: |-
          ./waka
          git config --global user.email "bot@github.com" && git config --global user.name "github-actions[bot]"
          git diff
          git add README.md && git commit -m "docs(README): :memo: update profile" || exit 0
          git pull && git push
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIST_ID: "595eec8ae8745b516c9a8ad8a265a100"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
