name: Update README Recent activity

on:
  schedule:
    - cron: '1 12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Update this repo's README with recent activity
        uses: jamesgeorge007/github-activity-readme@master
        with:
          COMMIT_MSG: 'docs: ðŸŽ‰ Update README with the recent activity'
          MAX_LINES: 15
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
